### ISSUE TITLE
Is it work with permission set?

### ISSUE THREAD

**Issue by rubicn** [amtrack/sfdx-plugin-source-read#29]
after testing it.
seems that is not working with permission set?

**Comment by amtrack** [comment]
As stated in the README:

> Disclaimer
> 
> Currently this has been tested only for Profiles and RecordTypes.

Can you explain your use case for PermissionSets?

**Comment by rubicn** [comment]
Sure,

Like profiles their is an issue with permission set.

I want to retrieve the entire permission set (100% include fields, objects, classes tabs and etc...)

**Comment by rubicn** [comment]
OK,
Maybe do you know about other solution?
thanks

**Comment by amtrack** [comment]
Unfortunately no.
