### ISSUE TITLE
Custom Profiles Not Working?

### ISSUE THREAD

**Issue by satishpersonal** [amtrack/sfdx-plugin-source-read#54]
Hi ,

I'm trying to use the Plugin and it works for Standard Profiles. But Custom profile it shows a empty xml File.

**Comment by amtrack** [comment]
@satishpersonal I'm not aware of any issues with custom Profiles.
- Do you mind sharing the command you're executing?
- Does the profile name contain any special characters?
- Does `sfdx force:source:retrieve -m "Profile:My Custom Profile"` work?

**Comment by satishpersonal** [comment]
@amtrack 

I have used below commands and below is what happening in my sandbox.

sfdx force:source:read -m "Profile:Admin" --> When i execute this command the profile is retrieved properly and metadata file has all permissions 

For Custom One's sfdx force:source:read -m "Profile:BC Sourcing" --> When i execute this command it creates a file but no permissions were written in the file not even user/system permissions.

Not sure if i understood it wrongly or what's going wrong.

**Comment by amtrack** [comment]
@satishpersonal I don't really have an idea what could be wrong.

Does `sfdx force:source:retrieve -m "Profile:My Custom Profile"` work?

**Comment by satishpersonal** [comment]
hi @amtrack ,

but then it only retrieves <userPermissions> or based on my package.xml i'm looking for the plugin help to retrieve the full profile metadata.

**Comment by amtrack** [comment]
@satishpersonal Yes, I just wanted to know if the `retrieve` command works (a.k.a executes successfully) with this custom profile or if it fails (because the profile name is incorrect for example).

**Comment by rcormier13** [comment]
@amtrack some more info on this issue. I had the same issue when I was connected to a non sandbox environment. Standard profiles worked but I got an empty file when trying to retrieve a custom profile. I was able to retrieve both profiles when I connected to a sandbox environment.
Hope this helps!

**Comment by amtrack** [comment]
> [@amtrack](https://github.com/amtrack) some more info on this issue. I had the same issue when I was connected to a non sandbox environment. Standard profiles worked but I got an empty file when trying to retrieve a custom profile. I was able to retrieve both profiles when I connected to a sandbox environment.
Hope this helps!

@rcormier13 I tried with a Scratch Org, Sandbox, Production and Developer Edition, but couldn't reproduce it.

If you can share a reproduction of this issue, this would be great.
