### ISSUE TITLE
Retrieve all Profiles creating * empty profile?

### ISSUE THREAD

**Issue by jonny-harte** [amtrack/sfdx-plugin-source-read#63]
Hi, I'm trying to retrive all Profiles in my repo but when I run the below command it keeps creating an additional *.profile-meta.xml file. Is there a way to get all profiles without creating this additional empty file?

`sfdx force:source:read -m "Profile"`

**Comment by amtrack** [comment]
Hi @jonny-harte, if you want to retrieve all Profiles which already exist in your repo, I suggest to use `-p` for the whole profiles folder:

```
sfdx force:source:read -p force-app/main/default/profiles
```

I think this does what you described without creating this `*.profile-meta.xml` file.

Wildcarding like `-m Profile` or `-m "Profile:*"` is not really supported in this plugin.
