### ISSUE TITLE
Add Option for Choosing Output Directory

### ISSUE THREAD

**Issue by Alfystar** [amtrack/sfdx-plugin-source-read#88]
**Description:**
Currently, there is no option to choose the output directory, which limits the flexibility of the project.

**Motivation**:
Users often need to organize the generated files in a specific way. Adding the ability to select the output directory would provide more flexibility for users integrating the project with other processes or projects.

Thank you for considering this request. I'm available for further details or clarifications if needed.

**Comment by Alfystar** [comment]
Forgive me, I have a question but I would avoid an issue to ask it:

In my scenario, we use sf-cli both locally and on a bamboo pipeline, inside the `package.json` we put the various npm dependencies, in the `devDependencies` key.

I noticed that, locally, after executing the installation commands you write in `README`, the following information appeared automatically inside `package.json`:

```json
 ...
 "dependencies": {
   "sfdx-plugin-source-read": "^1.2.0"
 },
 ...
```

As far as you know, is there a command that allows you to also update your sf plugin to be called by the pipeline at the begining?

Currently, for `prettier` (other tool) we already use
```bash
npm install --yes
```
And it takes the data from `package.json`.
So... is it enough to make sf install the latest version of your plugin if an update comes out?
Or do you have to have it installed "manually" on the pipeline agent every time?

Thanks in advance
Emanuele

**Comment by Alfystar** [comment]
@amtrack 
Any new about the output directory option?

**Comment by amtrack** [comment]
@Alfystar 

> Any new about the output directory option?

I currently don't plan to implement a `--output-dir` flag.

My personal experience with the `--output-dir` of the official `sf project retrieve start` command is not really good.
And I don't want to deal with those problems.

---

> Also target-org option can help

The `--target-org` flag already exists:

```console
sf force source read --help                                            
Read Metadata using the CRUD Metadata API

USAGE
  $ sf force source read -o <value> [--json] [-m <value>] [-p <value>]

FLAGS
  -m, --metadata=<value>    comma-separated list of metadata component names
                            Example: 'RecordType:Account.Business,Profile:Admin'
  -o, --target-org=<value>  (required) [default: test-yi7xt1f1tzo8@example.com] Username or alias of the target org.
  -p, --sourcepath=<value>  comma-separated list of source file paths to retrieve
                            Example: 'force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml,force
                            -app/main/default/profiles/Admin.profile-meta.xml'

GLOBAL FLAGS
  --json  Format output as json.

DESCRIPTION
  Read Metadata using the CRUD Metadata API

  Read Metadata using the CRUD Metadata API

EXAMPLES
  $ sf force source read -m "Profile:Admin"

  $ sf force source read -m "RecordType:Account.Business"

  $ sf force source read -p force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
```

**Comment by Alfystar** [comment]
Ok, thanks for the quick reply
For the output dir I "solved" in a homemade way

I rename the profile folder and put it in the file, then I recreate it, I create empty files in it, I start your tool. 
In the end, I just move the folder and restore the other one.

Anyway I'm actually seeing that output dir sometimes gets in the Anyway I'm actually seeing that output dir sometimes gets in the way 😅

**Comment by Alfystar** [comment]
Hi @amtrack 
Sorry to come back to this topic. At the moment, I have created a parallel retrieve system that can download an entire org in about 2 hours, parallelizing and packaging the resources. In creating this tool, I discovered many synchronization bugs that I also reported to sf-cli, and they solved them all.

The basis of this operation is the ability to download everything elsewhere, verify it, and then gather the sources to make a commit on the code repository.

It works perfectly, and I am really very satisfied with myself. At the moment, the only metadata that limits me in accelerating the process are the profiles. With your plugin, I have already completely solved our misalignment problem that too many times has broken the releases. However, if I can’t start more requests to the org in parallel, I have to wait in sequence for all the profile downloads to finish.

With the other metadata, I implemented parallelism using multiple output folders. But if you don’t think it’s easy to do it here too, could you at least work on a parameter that indicates how many parallel connections can be opened at most and, as soon as a retrieve finishes, immediately make the next profile in the list?

**Comment by amtrack** [comment]
Hi @Alfystar, I can try working on #51 to parallelise reading the metadata components.

**Comment by Alfystar** [comment]
I would be very happy to contribute, but unfortunately I am not an expert in creating plugins and I think I would slow you down 😅

**Comment by Alfystar** [comment]
I saw the new feature released!
As soon as I get a chance to test it I'll let you know how much time it saves!
THANK YOUU ... 😆
